name: Pipeline linter
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  linter:
  # especifico en qué ambiente va a correr la tarea automatizada, ex servidor ubuntu
    runs-on: ubuntu-lastest

    # especifico cuales son los pasos
    steps:
    # Obtener el código
      - name: Checkout code
      uses: actions/checkout@v2

      # Que va a usar y cual version
      - name: Use Noje.js
      uses: actions/setup-node@v2
      with: 
        node-version: '20.14'

      - name: Install dependencies
        run: npm install

      - name: Run linter
        run: npm run lint    
